#!/usr/bin/env bash


# GENERAL APT/SNAP UPDATE/UPGRADE
# ===============================
sudo apt update
sudo snap refresh


# GIT & related
# =============

sudo apt install git
sudo apt upgrade git

# Sublime Merge
# -------------
sudo snap install sublime-merge


# PYTHON & related
# ================

# Python & PIP
# ------------
sudo apt install python3 python3-pip
sudo apt upgrade python3 python3-pip
# note: remember to add /usr/.local/bin to your PATH

# Astral UV
# ---------
sudo snap install astral-uv


# NODE JS & related
# =================

# NodeJS & NPM
# ------------
sudo apt install nodejs npm
sudo apt upgrade nodejs npm


# DOCKER & related
# ================

# Docker & Docker Compose
# -----------------------
sudo apt install docker docker-compose
sudo apt upgrade docker docker-compose


# INTEGRATED DEVELOPMENT ENVIRONMENTS (IDEs)
# ==========================================

# Visual Studio Code
# ------------------
sudo snap install code

# Cursor
# ------
sudo curl https://cursor.com/install -fsS | bash

# Windsurf
# --------
# sudo apt install windsurf
# sudo apt upgrade windsurf


# CLOUD COMPUTING
# ===============

# AWS CLI
# -------
sudo snap install aws-cli --classic


# MISC / OTHER
# ============

# Postman
# -------
sudo snap install attr postman
