#!/usr/bin/env bash


# GENERAL APT/SNAP UPDATE/UPGRADE
# ===============================
sudo apt update
sudo snap refresh


# GIT & related
# =============

sudo apt install git gh
sudo apt upgrade git gh

# Sublime Merge
# -------------
sudo snap install sublime-merge


# PYTHON & related
# ================

# Python & PIP
# ------------
sudo apt install python3 python3-pip python3-setuptools
sudo apt upgrade python3 python3-pip python3-setuptools
# note: remember to add /usr/.local/bin to your PATH

# Astral UV
# ---------
sudo snap install astral-uv


# NODE JS & related
# =================

# NodeJS & NPM
# ------------
sudo apt install nodejs npm
sudo apt upgrade nodejs npm


# DOCKER & related
# ================

# Docker & Docker Compose
# -----------------------
sudo apt install docker docker-compose
sudo apt upgrade docker docker-compose

# KubeCtl
# -------
sudo snap install kubectl --classic

# Helm
# ----
sudo snap install helm --classic

# Kind
# ----
sudo apt install kind
sudo apt upgrade kind


# INTEGRATED DEVELOPMENT ENVIRONMENTS (IDEs)
# ==========================================

# Visual Studio Code
# ------------------
sudo snap install code

# Cursor
# ------
sudo curl https://cursor.com/install -fsS | bash

# Windsurf
# --------
# sudo apt install windsurf
# sudo apt upgrade windsurf


# CLOUD COMPUTING
# ===============

# AWS CLI
# -------
sudo snap install aws-cli --classic

# AWS EB CLI
# ----------
python3 -m pip install AWSEBCLI six --upgrade --user --break-system-packages


# MISC / OTHER
# ============

# Postman
# -------
sudo snap install attr postman
