#!/usr/bin/env bash


# PYTHON & related
# ================

# Python & PIP
# ------------
sudo apt install python3 python3-pip
sudo apt upgrade python3 python3-pip
# note: remember to add /usr/.local/bin to your PATH

# Astral UV
# ---------
sudo snap install astral-uv


# INTEGRATED DEVELOPMENT ENVIRONMENTS (IDEs)
# ==========================================

# Visual Studio Code
# ------------------
sudo snap install code
